### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v43-tier1-team-09#12]
**__Feature Description__**
Prepare for your Voyage by becoming familiar with the Chingu practices & procedures.

**__Major User Stories/tasks__**
- [ ] Getting Started: 🚀 Understand the Voyage Process #11 
- [ ] Getting Started: 📜 Review the Chingu Agile Methodology #2
- [ ] Getting Started: 🤔 Start thinking about project ideas & the technical stack #3 
- [ ] Getting Started: 🙋 Do you have questions about Chingu or the Voyage process? #4 

**__Additional Considerations__**
N/a

**Comment by mnichols08** [comment]
https://www.figma.com/file/Px3O3bPScjpjeWjcmRivdg/v43-09-team-library?node-id=0-1&t=TGbXi9DUTwgk5dmM-0
